### ISSUE TITLE
Crash: NullPointerException - android.media.MediaDrm.release/close() on a null object reference

### ISSUE THREAD

**Issue by a-blekot** [CleverTap/clevertap-segment-android#25]
```
com.clevertap.android:clevertap-android-sdk:4.7.5
com.clevertap.android:clevertap-segment-android:1.5.0
com.segment.analytics.android:analytics:4.10.1
```
In the last release of our app, we added CleverTap analytics to our code
Also in this release, we set the target SDK to 33....

Info from Crashlytics:

 - This crash event happened in the first 1-3 seconds of the user's session.
 - Devices: Unknown (29%), Samsung (18%), Honor (15%), Assus (12%), ...
 - OS: Android 12, 11, 10, **9 (26%), 8 (44%)**, 7, ...

> **Fatal Exception: java.lang.RuntimeException**
> Unable to create application com.myapp.App: java.lang.NullPointerException: Attempt to invoke virtual method '**void android.media.MediaDrm.release()**' on a null object reference

**or**

> Unable to create application com.myapp.App: java.lang.NullPointerException: Attempt to invoke virtual method '**void android.media.MediaDrm.close()**' on a null object reference

```
at com.segment.analytics.internal.Utils.getUniqueID(Utils.java:338)
at com.segment.analytics.internal.Utils.getDeviceId(Utils.java:304)
at com.segment.analytics.AnalyticsContext.putDevice(AnalyticsContext.java:239)
at com.segment.analytics.AnalyticsContext.create(AnalyticsContext.java:134)
at com.segment.analytics.Analytics$Builder.build(Analytics.java:1467)
at com.myapp.App.initCleverTap(App.kt:231)
at com.myapp.App.onCreate(App.kt:108)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791)
at android.app.ActivityThread.-wrap1()
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6541)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

That's how we set it up
```
class App : Application() {

    override fun onCreate() {
        ActivityLifecycleCallback.register(this)
        super.onCreate()
        
        initCleverTap()
    }
    
    private fun initCleverTap() {
        CleverTapAPI.setDebugLevel(
            if (BuildConfig.DEBUG) CleverTapAPI.LogLevel.DEBUG else CleverTapAPI.LogLevel.OFF
        )

        val analytics = Analytics.Builder(applicationContext, conf.segmentSourceWriteKey)
            .logLevel(if (BuildConfig.DEBUG) Analytics.LogLevel.VERBOSE else Analytics.LogLevel.NONE)
            .use(CleverTapIntegration.FACTORY)
            .trackApplicationLifecycleEvents() // Enable this to record certain application events automatically!
            .recordScreenViews() // Enable this to record screen views automatically!
            .build()

        Analytics.setSingletonInstance(analytics)
    }
```

**Comment by a-blekot** [comment]
maybe you mean `wvDrm != null`  🥲
```
           if (wvDrm == null) {
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
                    wvDrm.close();
                } else {
                    wvDrm.release();
                }
            }
```

**Comment by a-blekot** [comment]
O, I see it's already fixed!
https://github.com/segmentio/analytics-android/releases/tag/4.10.2

I will check if we can use [latest version ](https://github.com/segmentio/analytics-android/releases/tag/4.11.1)

**Comment by a-blekot** [comment]
O, I see it's already fixed!
https://github.com/segmentio/analytics-android/releases/tag/4.10.2

I will check if we can use [latest version](https://github.com/segmentio/analytics-android/releases/tag/4.11.1)
